// order matters
export const SKILL_LEVEL = {
  Beginner: 1,
  Competent: 2,
  Intermediate: 3,
  Skilled: 4,
  Pro: 5,
};

export const skillsData = [
  ["C# (C Sharp)", SKILL_LEVEL.Pro],
  [".NET", SKILL_LEVEL.Pro],  
  ["Java", SKILL_LEVEL.Skilled],
  ["Python", SKILL_LEVEL.Intermediate],
  ["JavaScript", SKILL_LEVEL.Pro],
  ["Node", SKILL_LEVEL.Intermediate],
  ["React", SKILL_LEVEL.Pro],
  ["Next.js", SKILL_LEVEL.Skilled],
  ["React Native", SKILL_LEVEL.Skilled],
  ["SQL Server", SKILL_LEVEL.Skilled],
  ["Azure", SKILL_LEVEL.Skilled],
  ["Azure Devops", SKILL_LEVEL.Skilled],
  ["Powershell", SKILL_LEVEL.Intermediate],
  ["Angular", SKILL_LEVEL.Competent],
  ["Vue", SKILL_LEVEL.Competent],
  ["jQuery", SKILL_LEVEL.Skilled],
  ["HTML", SKILL_LEVEL.Pro],
  ["CSS", SKILL_LEVEL.Pro],
  ["Bootstrap", SKILL_LEVEL.Pro],
  ["Bulma", SKILL_LEVEL.Skilled],
  ["PHP", SKILL_LEVEL.Intermediate],
  ["MySQL", SKILL_LEVEL.Intermediate],
  ["Git", SKILL_LEVEL.Pro],
  ["Docker", SKILL_LEVEL.Competent],
];
